---
logging:
  level:
    '[com.sap.cds.auditlog]': DEBUG
spring:
  web.resources.static-locations: "file:./app"
  jmx:
    enabled: true
cds:
  odata-v4.endpoint.path: "/api"
  odata-v4.serializer.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
  security:
    authentication.normalize-provider-tenant: true
    mock.users:
      admin:
        password: admin
        roles:
        - admin
        attributes:
          businessPartner:
          - "10401010"
      user:
        password: user
server.servlet.encoding:
  charset: UTF-8
  force: true
management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
    myhealth.enabled: true

---
spring:
  config.activate.on-profile: cloud
  sql.init.schema-locations: "classpath:schema-nomocks.sql"
cds:
  messaging.services:
    bupa-messaging:
      kind: enterprise-messaging
      format: cloudevents
      subscribe-prefix: sap/S4HANAOD/java/ce/
---
spring:
  config.activate.on-profile: ft
cds:
  model.provider.url: http://localhost:4005
  security.mock.users:
    admin:
      features:
      - isbn
      - discount
    user:
      features:
      - isbn

---
spring:
  config.activate.on-profile: local-mtxs
cds:
  security.mock.users:
    admin:
      tenant: t1
    user:
      tenant: t1

---
spring:
  config.activate.on-profile: default
cds:
  data-source:
    auto-config.enabled: false
